# Bounded compatibility/test changes to the hash-verified Parasail 2.6.2 source.
file(READ "${PARASAIL_SOURCE}/CMakeLists.txt" contents)
string(REPLACE "\${CMAKE_SOURCE_DIR}/data/test_small_2.fasta"
    "\${CMAKE_CURRENT_SOURCE_DIR}/data/test_small_2.fasta" contents "${contents}")
if(NOT contents MATCHES "STAR_CROSS_TEST_LIMIT")
    string(APPEND contents "\n# STAR_CROSS_TEST_LIMIT: avoid tiny-fixture OpenMP oversubscription\nset_tests_properties(test_verify PROPERTIES ENVIRONMENT \"OMP_NUM_THREADS=2\" TIMEOUT 120)\n")
endif()
file(WRITE "${PARASAIL_SOURCE}/CMakeLists.txt" "${contents}")

# Keep security fixes in the reproducible FetchContent patch step, including
# templates so regenerating SIMD kernels does not reintroduce narrow arithmetic.
file(GLOB security_sources "${PARASAIL_SOURCE}/src/*.c" "${PARASAIL_SOURCE}/util/templates/*.c")
foreach(path IN LISTS security_sources)
    file(READ "${path}" contents)
    set(original "${contents}")
    string(REPLACE "-segLen*gap" "-(int64_t)segLen*gap" contents "${contents}")
    if(path MATCHES "/memory\\.c$")
        string(REPLACE "if (a <= 0 || b <= 0)"
            "if (a <= 0 || b <= 0 || (size_t)a > INT_MAX / (size_t)b)" contents "${contents}")
    endif()
    if(contents MATCHES "STAR_CROSS_SECURITY_ARITHMETIC")
        if(NOT contents STREQUAL original)
            file(WRITE "${path}" "${contents}")
        endif()
        continue()
    endif()
    string(REPLACE "-open-gap*" "-(int64_t)open-(int64_t)gap*" contents "${contents}")
    if(path MATCHES "/memory(_sse|_avx2)?\\.c$")
        string(REPLACE "n * segLen" "(size_t)n * segLen" contents "${contents}")
        string(REPLACE "matrix->size*matrix->size" "(size_t)matrix->size*matrix->size" contents "${contents}")
        string(REPLACE "matrix->size*matrix->length" "(size_t)matrix->size*matrix->length" contents "${contents}")
        string(REPLACE "segLen = (s1Len + segWidth - 1) / segWidth;"
            "/* STAR_CROSS_PROFILE_BOUNDS: loop and matrix indices are int32_t. */\n    if (s1Len <= 0 || s1Len > INT32_MAX - (segWidth - 1) || n <= 0 || n > INT32_MAX / s1Len) return NULL;\n    segLen = (s1Len + segWidth - 1) / segWidth;"
            contents "${contents}")
        foreach(type IN ITEMS int int8_t int16_t int32_t int64_t)
            string(REPLACE "return (${type} *) parasail_memalign(alignment, size*sizeof(${type}));"
                "if (size > SIZE_MAX / sizeof(${type})) return NULL;\n    return (${type} *) parasail_memalign(alignment, size*sizeof(${type}));" contents "${contents}")
        endforeach()
    endif()
    if(NOT contents STREQUAL original)
        string(APPEND contents "\n/* STAR_CROSS_SECURITY_ARITHMETIC */\n")
        file(WRITE "${path}" "${contents}")
    endif()
endforeach()
file(READ "${PARASAIL_SOURCE}/parasail/memory.h" contents)
set(original "${contents}")
string(REPLACE "size_t _size = sizeof(type)*(count);"
    "size_t _count = (count); \\\n    if (_count > SIZE_MAX / sizeof(type)) return NULL; \\\n    size_t _size = sizeof(type)*_count;" contents "${contents}")
if(NOT contents STREQUAL original)
    file(WRITE "${PARASAIL_SOURCE}/parasail/memory.h" "${contents}")
endif()
foreach(vector IN ITEMS 128 256)
    if(vector EQUAL 128)
        set(path "${PARASAIL_SOURCE}/src/memory_sse.c")
    else()
        set(path "${PARASAIL_SOURCE}/src/memory_avx2.c")
    endif()
    file(READ "${path}" contents)
    set(original "${contents}")
    string(REPLACE "{\n    return (__m${vector}i *) parasail_memalign(alignment, size*sizeof(__m${vector}i));"
        "{\n    if (size > SIZE_MAX / sizeof(__m${vector}i)) return NULL;\n    return (__m${vector}i *) parasail_memalign(alignment, size*sizeof(__m${vector}i));" contents "${contents}")
    if(NOT contents STREQUAL original)
        file(WRITE "${path}" "${contents}")
    endif()
endforeach()
file(READ "${PARASAIL_SOURCE}/src/cpuid.c" contents)
if(NOT contents MATCHES "__s390x__")
    if(NOT contents MATCHES "defined\\(__PPC64__\\)")
        message(FATAL_ERROR "Parasail CPUID patch context changed")
    endif()
    string(REPLACE "defined(__PPC64__)"
        "defined(__PPC64__) || defined(__s390__) || defined(__s390x__)" contents "${contents}")
    file(WRITE "${PARASAIL_SOURCE}/src/cpuid.c" "${contents}")
endif()
